on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl:
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.36'
          - '5.38'
          - 'latest'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpm install -g --show-build-log-on-failure
      - run: prove -lv t
